### ISSUE TITLE
requires nesbot/carbon ^1.0

### ISSUE THREAD

**Issue by LPABelgium** [sarfraznawaz2005/servermonitor#2]
Hi !
First, thanks for your package, it seems to be a real good stuff ! Looking forward to give it a try !

But... Right now i can't install this package. Get this message : 
https://snag.gy/PDgWGZ.jpg (screenshot)

Netsbot Carbon 2.21 is currently installed.

Do you have a trick to work around this ?
I have to keep Carbon 2.21 installed for my app.

Thanks !

**Comment by sarfraznawaz2005** [comment]
Unfortunately version 2 has breaking changes. However, you may want to try this trick, in your composer.json file try something like this:

````
"require": {
    "nesbot/carbon": "2.x.x as 1.26.0"
},
````

Replace `2.x.x` with exact version you are using. Having said that, since version 2 has breaking changes, I am not 100% sure if this will work.
