### ISSUE TITLE
explode() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by 77media-creations** [sarfraznawaz2005/servermonitor#3]
Hi there, its a nice package I tried for my Laravel 5.6 project.

I has been working good at local machine but when I tried it live, it was giving this error upon clicking the Run All Checks button on UI page.

explode() expects parameter 2 to be string, object given {"exception":"[object] (ErrorException(code: 0): explode() expects parameter 2 to be string, object given at /home/user/public_html/vendor/sarfraznawaz2005/servermonitor/src/Senders/BaseSender.php:26)

**Comment by sarfraznawaz2005** [comment]
Can you please tell what `notification_channel` you are using ?

Also what output do you get in `dd` call if you use following code in `vendor/sarfraznawaz2005/ServerMonitor/src/Senders/BaseSender.php`:

````php
    public function getClassName($namespace)
    {
        try {

            $path = explode('\\', $namespace);
        } catch (\Exception $e) {
            dd($namespace);
        }

        return array_pop($path);
    }
````
