### ISSUE TITLE
Disabling 'web_interface_enabled' makes "php artisan route:list" fail

### ISSUE THREAD

**Issue by PollieDev** [sarfraznawaz2005/servermonitor#4]
When you disable the `web_interface_enabled` option and head to the route it returns a 404 (as it should). But if you use `php artisan route:list` it apparently hits the `__construct` and thereby also errors out on the `abort()`

Here the error with trace:
```
   Symfony\Component\HttpKernel\Exception\NotFoundHttpException  :

  at /Users/admin/sites/floristo-new/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:1020
    1016|      */
    1017|     public function abort($code, $message = '', array $headers = [])
    1018|     {
    1019|         if ($code == 404) {
  > 1020|             throw new NotFoundHttpException($message);
    1021|         }
    1022|
    1023|         throw new HttpException($code, $message, null, $headers);
    1024|     }

  Exception trace:

  1   Illuminate\Foundation\Application::abort("", [])
      /Users/admin/sites/floristo-new/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:46

  2   abort()
      /Users/admin/sites/floristo-new/vendor/sarfraznawaz2005/servermonitor/src/Http/Controllers/ServerMonitorController.php:23

  3   Sarfraznawaz2005\ServerMonitor\Http\Controllers\ServerMonitorController::__construct(Object(Sarfraznawaz2005\ServerMonitor\ServerMonitor))
      [internal]:0
```

I myself am not the best package developer but wouldn't it be more efficient to do an if statement around the `Route::group()` in `routes.php` instead of in `__construct()`? This wouldlet  Laravel not even be aware of the route and as far as my testing went it should not fail when checking `route:list`

Thanks in advance for the package and having a look into this.

**Comment by sarfraznawaz2005** [comment]
@PollieDev thanks for pointing out. It is fixed in v 1.9.2 so please try updating. thx
