### ISSUE TITLE
Can't install in Laravel version 6

### ISSUE THREAD

**Issue by belipero** [sarfraznawaz2005/servermonitor#6]
Hi!
I executed **composer require sarfraznawaz2005/servermonitor** and I recieved the following error: 

![image](https://user-images.githubusercontent.com/16259323/89133856-00e0d780-d4f6-11ea-92f2-f1da561cd1b0.png)

So I executed guzzle instalation:

`"require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^7.0",
        "laravel/framework": "^6.2",
        "laravel/socialite": "^4.3",
        "laravel/telescope": "^3.1",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^1.1",
        "mpdf/mpdf": "^8.0",
        "owen-it/laravel-auditing": "^10.0",
        "spatie/laravel-cors": "^1.6"
    },`

I executed again server monitor installation and now I recieved this error:

![image](https://user-images.githubusercontent.com/16259323/89133879-4a312700-d4f6-11ea-95c4-9b52bfb9f540.png)

Do you have a workaround for this issue?

Regards

**Comment by connecteev** [comment]
Agreed. Would be great if this package was maintained actively - it's really comprehensive and well-done.

**Comment by Faks** [comment]
Hi, laravel 6 is outdated version pleasee update framework, and author please close ticket old versions should never be supported.
